### ISSUE TITLE
Outer circle, no apps

### ISSUE THREAD

**Issue by kaisercode-dev** [paavu/floatoo#2]
I assign apps to the outer circle, but it often loads with nothing there. They sometimes show up and sometimes not. If i open it and close it the app shortcuts appear, but then have disappeared the next time i use it.

**Comment by paavu** [comment]
I think you are missing the point that Each first-level shortcut has it own
independent outer circle.
You might have added the shortcuts on the outer circle of one shortcut and
looking into outer-circle of other first-level shortcut

Please validate and confirm
Thank you

Best Regards
Aneesh Chopra

**Comment by kaisercode-dev** [comment]
🤦Doh! Now i see. I didn't know this and that explains a lot. Brilliant app by the way. I upgraded to pro. Thanks for the prompt reply.

**Comment by paavu** [comment]
Glad that I managed to help with your query. 
I appreciate that you wrote back with your doubt.
Most of the users actually just left negative comments and uninstall complex apps when they are unable to understand or use them.
Thanks a lot that you liked my app and upgraded to pro :)

I request and appreciate again if you also left a 5star rating/comment on play store.

Keep using Floatoo. I have many more features in future updates.

NOTE:
In case, if floatoo sidebar stops working but the accessibility service still shows on.
just forced stop and restart the app to reconnect accessibility service properly

Best Regards
Aneesh Chopra
