### ISSUE TITLE
Can't backup or restore on android 11,tab s7

### ISSUE THREAD

**Issue by TheTerribleIvan** [paavu/floatoo#3]
There's no allow storage access option , so i can't make a backup or restore 
![Screenshot_20210413-045722_Permission controller](https://user-images.githubusercontent.com/82439192/114517503-c860d400-9c14-11eb-9f0c-ff6725016457.jpg)

**Comment by paavu** [comment]
With Android 11, External storage permission is forbidden.
Hence, I moved the Backup and storage to Google account.

Please ensure that the latest version and Google account is logged in on
your android.
on backup/restore action, the application asks for Google drive access.
just allow and app will sync your backup/restore to your google drive.

Please let me know if you still unable to use backup/restore functionality

Best Regards
Aneesh Chopra

Founder | CTO
https://paavu.com
